apiVersion: machineconfiguration.openshift.io/v1
kind: MachineConfig
metadata:
  labels:
        machineconfiguration.openshift.io/role: worker
  name: 50-middle-worker-chrony
spec:
  config:
    ignition:
      version: 2.2.0
    storage:
      files:
      - contents:
          source: data:,server%200.fedora.pool.ntp.org%0A%0Aserver%201.fedora.pool.ntp.org%0A%0Aserver%202.fedora.pool.ntp.org%0A%0Adriftfile%20/var/lib/chrony/drift%0A%0Amakestep%201.0%203%0A%0Artcsync%0A%0Akeyfile%20/etc/chrony.keys%0A%0Aleapsectz%20right/UTC%0A%0Alogdir%20/var/log/chrony%0A
        filesystem: root
        mode: 0644
        path: /tmp/testdata.conf
